stages:
  - build

before_script:
  - apt-get update -qq
  - apt-get install -q -y build-essential python-cffi python3-cffi libffi-dev
  - apt-get install -q -y python-all python3-all python-dev python3-dev
  - apt-get install -q -y python-setuptools python3-setuptools python-pip
  - apt-get install -q -y rpm tar gzip bzip2
  - pip install -U pip
  - pip install -r requirements.txt
  - make clean

build-jessie:
  when: always
  stage: build
  image: debian:jessie
  script:
    - git submodule update --init --recursive
    - make -j 4
    - make install
  artifacts:
    paths:
      - dist/ocspd*.tar.gz
      - dist/ocspd*.rpm
      - dist/ocspd*.whl
      - dist/ocspd*.tar.bz2
      - dist/ocspd*.deb

build-stretch:
  when: always
  stage: build
  image: debian:stretch
  script:
    - git submodule update --init --recursive
    - make -j 4
    - make install
  artifacts:
    paths:
      - dist/ocspd*.tar.gz
      - dist/ocspd*.rpm
      - dist/ocspd*.whl
      - dist/ocspd*.tar.bz2
      - dist/ocspd*.deb
