stages:
  - build

before_script:
  - apt-get update -qq
  - apt-get install -q -y build-essential
  - make -v
  - make clean

build-jessie:
  stage: build
  image: debian:jessie-slim
  script:
    - make
  artifacts:
    paths:
      - dist/ocspd*.tar.gz
      - dist/ocspd*.rpm
      - dist/ocspd*.whl
      - dist/ocspd*.tar.bz2
      - dist/ocspd*.deb


build-stretch:
  stage: build
  image: debian:stretch-slim
  script:
    - make
  artifacts:
    paths:
      - dist/ocspd*.tar.gz
      - dist/ocspd*.rpm
      - dist/ocspd*.whl
      - dist/ocspd*.tar.bz2
      - dist/ocspd*.deb
