stages:
  - build

before_script:
  - apt-get update -qq
  - apt-get install -q -y build-essential
  - make clean

build-jessie:
  stage: build
  image: debian:jessie-slim
  script:
    - make
  artifacts:
    paths:
      - dist/ocspd_*
      - dist/python-ocspd_*
      - dist/python3-ocspd_*

build-stretch:
  stage: build
  image: debian:stretch-slim
  script:
    - make
  artifacts:
    paths:
      - dist/ocspd_*
      - dist/python-ocspd_*
      - dist/python3-ocspd_*
