stages:
- build-containers
- build-compile
- test

variables:
  DOCKER_DRIVER: overlay2
  #GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_FILES_URL: docker.greenhost.net/open/ocspd

build:build-container:
  image: docker:latest
  services:
  - docker:dind
  stage: build-containers
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.greenhost.net
  - docker build -t $DOCKER_FILES_URL/build-stretch:$CI_COMMIT_REF_NAME -f ./docker/build-stretch/Dockerfile ./
  - docker push $DOCKER_FILES_URL/build-stretch:$CI_COMMIT_REF_NAME

build:test-jessie:
  image: docker:latest
  services:
  - docker:dind
  stage: build-containers
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.greenhost.net
  - docker build -t $DOCKER_FILES_URL/test-jessie:$CI_COMMIT_REF_NAME ./docker/test-jessie/
  - docker push $DOCKER_FILES_URL/test-jessie:$CI_COMMIT_REF_NAME

build:test-stretch:
  image: docker:latest
  services:
  - docker:dind
  stage: build-containers
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.greenhost.net
  - docker build -t $DOCKER_FILES_URL/test-stretch:$CI_COMMIT_REF_NAME ./docker/test-stretch/
  - docker push $DOCKER_FILES_URL/test-stretch:$CI_COMMIT_REF_NAME

build:test-pypy25:
  image: docker:latest
  services:
  - docker:dind
  stage: build-containers
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.greenhost.net
  - docker build -t $DOCKER_FILES_URL/test-pypy25:$CI_COMMIT_REF_NAME ./docker/test-pypy25/
  - docker push $DOCKER_FILES_URL/test-pypy25:$CI_COMMIT_REF_NAME

build:test-pypy35:
  image: docker:latest
  services:
  - docker:dind
  stage: build-containers
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.greenhost.net
  - docker build -t $DOCKER_FILES_URL/test-pypy35:$CI_COMMIT_REF_NAME ./docker/test-pypy35/
  - docker push $DOCKER_FILES_URL/test-pypy35:$CI_COMMIT_REF_NAME

build:stretch:
  stage: build-compile
  image: build-containers:$CI_COMMIT_REF_NAME
  script:
  - git submodule update --init --recursive
  - pip install --user -r requirements.txt
  - make clean
  - make
  artifacts:
    paths:
    - dist/stapled*.tar.gz
    - dist/stapled*.rpm
    - dist/stapled*.whl
    - dist/stapled*.tar.bz2
    - dist/stapled*.deb

test:jessie:python2:
  stage: test
  image: test-jessie:$CI_COMMIT_REF_NAME
  script:
  - dpkg -i ./dist/stapled-py2_*all.deb
  - openssl version
  - ./refresh_testdata.sh
  - stapled -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch
  artifacts:
    when: always
    paths:
    - testdata/

test:jessie:python3:
  stage: test
  image: test-jessie:$CI_COMMIT_REF_NAME
  script:
  - dpkg -i ./dist/stapled_*all.deb
  - openssl version
  - ./refresh_testdata.sh
  - stapled -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch

test:stretch:python2:
  stage: test
  image: test-stretch:$CI_COMMIT_REF_NAME
  script:
  - apt-get install -y -q ./dist/stapled-py2_*all.deb
  - openssl version
  - ./refresh_testdata.sh
  - stapled -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch

test:stretch:python3:
  stage: test
  image: test-stretch:$CI_COMMIT_REF_NAME
  script:
  - apt-get install -y -q ./dist/stapled_*all.deb
  - openssl version
  - ./refresh_testdata.sh
  - stapled -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch

test:pypy2:
  stage: test
  image: test-pypy25:$CI_COMMIT_REF_NAME
  script:
  - dpkg -i ./dist/stapled-py2_*all.deb
  - ./refresh_testdata.sh
  - stapled -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch

test:pypy3:
  stage: test
  image: test-pypy35:$CI_COMMIT_REF_NAME
  script:
  - dpkg -i ./dist/stapled_*all.deb
  - ./refresh_testdata.sh
  - stapled -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch
