stages:
- build
- test

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"

build:stretch:
  stage: build
  image: debian:stretch
  script:
  - apt-get update -qq
  - apt-get install -q -y build-essential python-cffi python3-cffi libffi-dev python-all python3-all python-dev python3-dev python-setuptools python3-setuptools python-pip rpm tar gzip bzip2 git debhelper
  - pip install -U pip
  - pip install -r requirements.txt
  - git submodule update --init --recursive
  - make clean
  - make
  artifacts:
    paths:
    - dist/ocspd*.tar.gz
    - dist/ocspd*.rpm
    - dist/ocspd*.whl
    - dist/ocspd*.tar.bz2
    - dist/ocspd*.deb

test:stretch:python3:
  stage: test
  image: debian:stretch
  script:
  - apt-get update
  - apt-get install -y openssl
  - apt-get install -y -q ./dist/ocspd_*all.deb
  - openssl version
  - ./refresh_testdata.sh
  - ocspd -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch
  artifacts:
    when: always
    paths:
    - testdata/

test:jessie:python3:
  stage: test
  image: debian:jessie
  script:
  - echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
  - apt-get update
  - apt-get install -y -t jessie-backports python3-configargparse python3-daemon python3-future
  - apt-get install -y openssl python3-six python3-cffi
  - dpkg -i ./dist/ocspd-py2_*all.deb
  - openssl version
  - ./refresh_testdata.sh
  - ocspd -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch
  artifacts:
    when: always
    paths:
    - testdata/

test:stretch:python2:
  stage: test
  image: debian:stretch
  script:
  - apt-get update
  - apt-get install -y openssl
  - apt-get install -y -q ./dist/ocspd_*all.deb
  - openssl version
  - ./refresh_testdata.sh
  - ocspd -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch
  artifacts:
    when: always
    paths:
    - testdata/

test:jessie:python2:
  stage: test
  image: debian:jessie
  script:
  - echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
  - apt-get update
  - apt-get install -y -t jessie-backports python-configargparse python-daemon python-future
  - apt-get install -y openssl python-six python-cffi
  - dpkg -i ./dist/ocspd-py2_*all.deb
  - openssl version
  - ./refresh_testdata.sh
  - ocspd -d testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls testdata/**/chain.pem.ocsp
  dependencies:
  - build:stretch
  artifacts:
    when: always
    paths:
    - testdata/
