stages:
- build-containers
- unit-tests
- build-compile
- functional-tests

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_FILES_URL: docker.greenhost.net/open/stapled
  BUILD_COMPILE_CONTAINER: $DOCKER_FILES_URL/build-stretch:$CI_COMMIT_REF_NAME
  STRETCH_TEST_CONTAINER: $DOCKER_FILES_URL/test-stretch:$CI_COMMIT_REF_NAME
  JESSIE_TEST_CONTAINER: $DOCKER_FILES_URL/test-jessie:$CI_COMMIT_REF_NAME
  GIT_SUBMODULE_STRATEGY: recursive

build:build-container:
  image: docker:latest
  services:
  - docker:dind
  stage: build-containers
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.greenhost.net
  - docker pull $BUILD_COMPILE_CONTAINER || true
  - docker build --pull --cache-from $BUILD_COMPILE_CONTAINER -t $BUILD_COMPILE_CONTAINER -f ./docker/build-stretch/Dockerfile ./
  - docker push $BUILD_COMPILE_CONTAINER

build:test-jessie:
  image: docker:latest
  services:
  - docker:dind
  variables:
    GIT_STRATEGY: fetch
  stage: build-containers
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.greenhost.net
  - docker pull $JESSIE_TEST_CONTAINER || true
  - docker build --pull --cache-from $JESSIE_TEST_CONTAINER -t $JESSIE_TEST_CONTAINER ./docker/test-jessie/
  - docker push $JESSIE_TEST_CONTAINER

build:test-stretch:
  image: docker:latest
  services:
  - docker:dind
  variables:
    GIT_STRATEGY: fetch
  stage: build-containers
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.greenhost.net
  - docker pull $STRETCH_TEST_CONTAINER || true
  - docker build --pull --cache-from $STRETCH_TEST_CONTAINER -t $STRETCH_TEST_CONTAINER ./docker/test-stretch/
  - docker push $STRETCH_TEST_CONTAINER

build:compile:
  stage: build-compile
  image: $BUILD_COMPILE_CONTAINER
  script:
  - which python3 && $(which python3) --version
  - openssl version
  - pip3 install --user -r requirements.txt
  - make clean
  - make
  artifacts:
    paths:
    - dist/stapled*.tar.gz
    - dist/stapled*.rpm
    - dist/stapled*.whl
    - dist/stapled*.tar.bz2
    - dist/stapled*.deb

test:jessie:python2:
  stage: functional-tests
  image: $JESSIE_TEST_CONTAINER
  variables:
    GIT_STRATEGY: none
  script:
  - which python && $(which python) --version
  - openssl version
  - dpkg -i ./dist/stapled-py2_*all.deb
  - openssl version
  - ./refresh_testdata.sh
  - stapled -p /tmp/testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls /tmp/testdata/**/chain.pem.ocsp
  dependencies:
  - build:compile

unit:python2:
  stage: unit-tests
  image: python:2.7-stretch
  script:
  - which python && $(which python) --version
  - pip install -r requirements.txt
  - pytest -v

unit:python3:
  stage: unit-tests
  image: python:3.6-stretch
  script:
  - which python && $(which python) --version
  - pip3 install -r requirements.txt
  - pytest -v

test:jessie:python3:
  stage: functional-tests
  image: $JESSIE_TEST_CONTAINER
  variables:
    GIT_STRATEGY: none
  script:
  - which python3 && $(which python3) --version
  - openssl version
  - dpkg -i ./dist/stapled_*all.deb
  - ./refresh_testdata.sh
  - stapled -p /tmp/testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls /tmp/testdata/**/chain.pem.ocsp
  dependencies:
  - build:compile

test:stretch:python2:
  stage: functional-tests
  image: $STRETCH_TEST_CONTAINER
  variables:
    GIT_STRATEGY: none
  script:
  - which python && $(which python) --version
  - openssl version
  - apt-get install -y -q ./dist/stapled-py2_*all.deb
  - ./refresh_testdata.sh
  - stapled -p /tmp/testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls /tmp/testdata/**/chain.pem.ocsp
  dependencies:
  - build:compile

test:stretch:python3:
  stage: functional-tests
  image: $STRETCH_TEST_CONTAINER
  variables:
    GIT_STRATEGY: none
  script:
  - which python3 && $(which python3) --version
  - openssl version
  - apt-get install -y -q ./dist/stapled_*all.deb
  - ./refresh_testdata.sh
  - stapled -p /tmp/testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls /tmp/testdata/**/chain.pem.ocsp
  dependencies:
  - build:compile

test:dev-setup:
  stage: build-compile
  image: python:3.6-stretch
  script:
  - which python3 && $(which python3) --version
  - openssl version
  - pip3 install -e .
  - ./refresh_testdata.sh
  - stapled -p /tmp/testdata/ --recursive --interactive --no-haproxy-sockets -vvvv &
  - sleep 30
  - ls /tmp/testdata/**/chain.pem.ocsp
