
stages:
  - clean
  - build

clean:
  script:
    - make clean

build:
  stage: build
      - make build
  artifacts:
    paths:
    - dist/ocspd_*
    - dist/python-ocspd_*
    - dist/python3-ocspd_*
