#!/bin/sh

if test -d /etc/stapled ; then
	if ! find /etc/stapled/ -type f >/dev/null ; then
		rmdir /etc/stapled
	fi
	rm lib/systemd/system/stapled.service
	systemctl disable stapled
	systemctl daemon-reload
fi
